name: Run Login Script

on:
  workflow_dispatch:
  schedule:
    - cron: "39 16 */5 * *"   # 每5天的UTC时间16:15，即北京时间的凌晨12:39  
    - cron: "17 17 */11 * *"   # 每11天的UTC时间17:17，即北京时间的凌晨1:17  
  push:
    branches:
      - main

jobs:
  login:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout 仓库代码  
        uses: actions/checkout@v2
        
      - name: 安装 Playwright 所需依赖  
        run: |
          npx playwright install-deps

      - name: 设置 Python 环境  
        uses: actions/setup-python@v2  
        with:
          python-version: '3.10'

      - name: 缓存 Python 依赖  
        uses: actions/cache@v2  
        with:
          path: |
            ~/.cache/pip  
          key: ${{ runner.os }}-python-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-python-

      - name: 安装python脚本所需依赖  
        run: |
          python -m pip install --upgrade pip  
          pip install playwright aiofiles requests

      - name: 安装 Playwright 浏览器  
        run: |
          playwright install firefox  
          
      - name: 创建WARP网络  
        uses: fscarmen/warp-on-actions@v1.3  
        with:
           stack: dual        # Optional. Support [ ipv4, ipv6, dual ]. Default is dual.
           mode: client       # Optional. Support [ wireguard, client ]. Default is wireguard.

      - name: 运行自动化登录脚本  
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          WEBHOST: ${{ secrets.WEBHOST }}
        run: |
          python login_script.py || {
            echo "脚本运行失败，正在发送通知..."
            curl -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
              -d "chat_id=${{ secrets.TELEGRAM_CHAT_ID }}&text=自动化登录脚本运行失败！"
          }
